#----------------------------------------------------------------------
# This file was generated by img2py.py
#
# Source file is kcmmemory.png from KDE icons

import wx
import pickle

def getkcmmemoryData(): return pickle.loads(
b"(lp1\nS'32 32 8 1'\naS'@ c Black'\naS'. c #303030'\naS'# c #C0C0C0'\naS'+ c\
 #D8DCD8'\naS'O c #808080'\naS'  c None'\naS'o c #585858'\naS'X c #A0A0A0'\n\
aS'                                '\naS'                                '\n\
aS'                ..              '\naS'               .XXo.O..         '\n\
aS'              .O++. ..o@        '\naS'              .O+.X..o@Oo       '\n\
aS'            ..o..X..o@o..O      '\naS'           .XXo.X....X..#..     '\n\
aS'          .O++.X......XX....    '\naS'          .O+.O............O@   '\n\
aS'        ..o..X............X@@   '\naS'       .XXo.O............X@@@@  '\n\
aS'      .O++.X............X@@@X@  '\naS'      .O+.O...@...@...@X@@@+Xo  '\n\
aS'    ..o..O.@.@.@.@.@.@X@@@++XXo '\naS'   .XXo.O.@.@.@.@.@.@O@@@@@+Ooo '\n\
aS'  .O++.O.@.@.@.@.@.@X@@@X@ .oo  '\naS'  .O+.O@@.@@@.@@@.@O@@@+Xo X.O  '\n\
aS'  o..O@@@@@@@@@@@@X@@@++XXo .   '\naS'  . @@O@@@@@@@@@@O@@@@@+Ooo .   '\n\
aS'  . @@@O@@@@@@@@O@@@X@ .ooX     '\naS'    @@@@O@@@@@@O@@@+Xo X.O      '\n\
aS'     @@@@O@@@@O@@@++XXo .       '\naS'     @@@@@O@@O@@@@@+Ooo .       '\n\
aS'      @@@@@OO@@@X@ .ooX         '\naS'       @@@@.o@@+Xo X.O          '\n\
aS'        @@@@.@++XXo .           '\naS'         @@@.@@+Ooo .           '\n\
aS'          @.@. .ooX             '\naS'               X.O              '\n\
aS'                .               '\naS'                .               '\n\
a." )

def getkcmmemoryBitmap(): return wx.Bitmap(getkcmmemoryData(),type=wx.BITMAP_TYPE_XPM_DATA)
def getkcmmemoryImage(): return wx.ImageFromBitmap(getkcmmemoryBitmap(),type=wx.BITMAP_TYPE_BMP)
